### ISSUE TITLE
Bug: bg entitlements_createsuborgs isn't respected 

### ISSUE THREAD

**Issue by drdamour** [mulesoft-anypoint/terraform-provider-anypoint#16]
have a bg like

```
resource "anypoint_bg" "jrs_it_apps" {
  name                   = "Example"
  parent_organization_id = local.org_id
  owner_id               = local.bg_owner_id
  # we allow suborgs for the bg per app approach we are piloting
  entitlements_createsuborgs      = false
  entitlements_createenvironments = true
}
```

i switched entitlements_createsuborgs to true and ran a plan, and there were no changes shown.  seems liek fetch of current state doesn't read this right or map it right.

sniffing the request i see in the json response createSubOrgs=True when i enable it in web ux, and false when i disable it, so anypoint services seem to be functioning.

i also noticed on a straight create it doesn't seem to mark the create sub groups flag in the ux when set to true, sniffing the create POST request i see `createSubOrgs=False`

so def looks like a mistake in the mapping of hcl to json doc

**Comment by soufi** [comment]
Hiya @drdamour, 

Thanks for reporting this, I will investigate.

**Comment by shimiz98** [comment]
Hello, I have same problem. 

I think one of the causes is that function [DiffSuppressFunc()](https://github.com/mulesoft-anypoint/terraform-provider-anypoint/blob/ea2765d6d98921c13838905b02d5e6d4c653d6ef/anypoint/resource_bg.go#L205) in `entitlements_createsuborgs` is something wrong.

Since DiffSuppressFunc() calls [DiffSuppressFunc4OptionalPrimitives()](https://github.com/mulesoft-anypoint/terraform-provider-anypoint/blob/ea2765d6d98921c13838905b02d5e6d4c653d6ef/anypoint/util.go#L109), I have temporarily added a log to DiffSuppressFunc4OptionalPrimitives().

When, I switched `entitlements_createsuborgs` to true and ran a plan, DiffSuppressFunc4OptionalPrimitives() was called and that returns true(true means suppress change), so there were no changes shown.

Here is the log I added.
```diff
 func DiffSuppressFunc4OptionalPrimitives(k, old, new string, d *schema.ResourceData, initial string) bool {
+       var result bool
        if new == initial {
-               return true
+               result = true
        } else {
-               return old == new
+               result = (old == new)
        }
+       log.Printf("[INFO] DiffSuppressFunc4OptionalPrimitives result=%v key=%s old=%s new=%s initial=%s", result, k, old, new, initial)
+       return result
 }
```

if `entitlements_createsuborgs` is true, then return true
```
2023-10-16T00:36:15.407+0900 [INFO]  provider.terraform-provider-anypoint.exe: DiffSuppressFunc4OptionalPrimitives result=true key=entitlements_createsuborgs old=false new=true initial=true: timestamp="2023-10-16T00:36:15.407+0900"
```

* DiffSuppressFunc()  true means suppress change
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#SchemaDiffSuppressFunc

I see that DiffSuppressFunc was added in [another issue](https://github.com/mulesoft-consulting/terraform-provider-anypoint/pull/52), but I have yet to catch up on my understanding of the issue. 
I am still not sure how to fix this problem as in other cases I have changed the value in the web console but the plan were no changes shown with below WARN log.

```
2023-10-15T22:39:25.913+0900 [WARN]  Provider "registry.terraform.io/mulesoft-anypoint/anypoint" produced an unexpected new value for anypoint_bg.devb during refresh.
      - .updated_at: was cty.StringVal("2023-10-15T12:33:30.722Z"), but now cty.StringVal("2023-10-15T13:39:16.266Z")
      - .entitlements_createsuborgs: was cty.False, but now cty.True
```

**Comment by soufi** [comment]
Hi @drdamour and @shimiz98, 

I fixes the issue on the branch fix/issue-16. 
Can you please test on your side to confirm resolution before I release the fix ? 

Thank you.

**Comment by soufi** [comment]
Hello, 

New version v1.5.6 published with the fix.

**Comment by drdamour** [comment]
@soufi got soem unexpected defaults now

![image](https://github.com/mulesoft-anypoint/terraform-provider-anypoint/assets/1514496/388d93da-d9dd-4311-a0ed-1e695dfa37ce)

this bg was created with prior version...so thinking this is the provider changing it's defaults

**Comment by soufi** [comment]
Hi @drdamour, 
I had to realign the default values with the platform's default values in order to avoid unnecessary changes after the first creation. 
This was necessary after the correction of the bug. Sorry for the inconvenience.
